Remove check for /post-new.php when populating custom fields
pods-framework/pods pull request #5919
Opened 2021-01-13 20:00 UTC by Chouby

## Description

Fixes #5879

If a **new post** is pre-filled with custom fields, the custom fields values are not populated in the custom fields metabox.
This PR removes the check for `/post-new.php` in order to populate the fields eve for new posts.

## How Has This Been Tested?

Manual test, following the steps described in the issue #5879.

## Types of changes

Bug fix

## Changelog text for these changes

Fix custom fields values not prefilled when creating a post translation with Polylang.

## PR Checklist

- [ ] My code is tested.
- [x] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.
- [ ] My code includes automated tests for PHP and/or JS (if applicable).

2021-01-14 08:28 UTC, lkraav commented
But what's the original reasoning for having post-new.php check?

2021-01-14 13:00 UTC, JoryHogeveen commented
Good point @lkraav 

Previous commits: 
- Initial change: https://github.com/pods-framework/pods/commit/6a682940eba92b0f3a9b0eda5380e76bb023d0b8
  - Issue: https://github.com/pods-framework/pods/issues/716
- Minor modification: https://github.com/pods-framework/pods/commit/afa40c855e9a576347edcbd9472bc90af276ff84
  - Issue: https://github.com/pods-framework/pods/issues/2034

2021-03-03 15:00 UTC, sc0ttkclark commented
Definitely worth doing some extended testing to confirm we don't break default values for Posts or CPTs on this. Need to test in classic and in block editor.

2021-04-16 04:17 UTC, sc0ttkclark commented
@JoryHogeveen Pending further testing to see if you can find out why this may have been needed before (classic/gutenberg testing)

2021-04-19 16:47 UTC, sc0ttkclark approved these changes

2021-04-19 17:34 UTC, JoryHogeveen commented
Testes and this change indeed removes all default values.

2021-04-19 17:53 UTC, JoryHogeveen commented
Created a new PR since I cannot access this branch. #5997

2021-04-19 17:53 UTC, JoryHogeveen requested changes
Disables Pods default values entirely.
Fix available in this PR: https://github.com/pods-framework/pods/pull/5997

2021-04-19 22:09 UTC, closed without merging

2021-04-20 17:01 UTC, Chouby commented
> Created a new PR since I cannot access this branch. #5997
@JoryHogeveen Sorry for this. Not sure why the option was unchecked :/

2021-04-21 09:59 UTC, JoryHogeveen commented
No problem, it's still a nice find on which I could continue, I've added you to the changelog credits, thank you!